Run poetry run flake8 example/
The "poetry.dev-dependencies" section is deprecated and will be removed in a future version. Use "poetry.group.dev.dependencies" instead.
example/simple_app.py:3:80: E501 line too long (80 > 79 characters)
Error: Process completed with exit code 1.